name: Combined-filtering-of-source

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  generate-filtered-source:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name:  Generate ALTAIRBASIC30_ASM_LINES.LST
        shell: pwsh
        run: |
          Get-Content .\ALTAIRBASIC30.LST | 
          ForEach-Object -Begin { $counter = 0; $pageNumber = 1 } -Process {
              $counter++
              $pagePosition = ($counter - 1) % 67 + 1
              
              # Skip first page
              if ($pageNumber -eq 1) {
                  if ($counter % 67 -eq 0) {
                      $pageNumber++
                      $counter = 0
                  }
                  return
              }
              
              # Skip pages 165-198
              $lineStart = ($pageNumber - 1) * 67 + 1
              if ($lineStart -ge (165 * 67) -and $lineStart -le (198 * 67)) {
                  if ($counter % 67 -eq 0) {
                      $pageNumber++
                      $counter = 0
                  }
                  return
              }
              
              # Stop after page 301
              if ($pageNumber -gt 301) {
                  return
              }
              
              # Output only lines 7-59 of each valid page, trimming first 40 characters
              if ($pagePosition -gt 6 -and $pagePosition -lt 60) {
                  if ($_.Length -gt 40) {
                      Write-Output $_.Substring(40)
                  }
              }
              
              if ($counter % 67 -eq 0) {
                  $pageNumber++
                  $counter = 0
              }
          } | Out-File -FilePath ALTAIRBASIC30_ASM_LINES.LST

      - name: Generate ALTAIRBASIC30_ASM_NOLINES.LST
        shell: pwsh
        run: |
          Get-Content .\ALTAIRBASIC30.LST | 
          ForEach-Object -Begin { $counter = 0; $pageNumber = 1 } -Process {
              $counter++
              $pagePosition = ($counter - 1) % 67 + 1
              
              # Skip first page
              if ($pageNumber -eq 1) {
                  if ($counter % 67 -eq 0) {
                      $pageNumber++
                      $counter = 0
                  }
                  return
              }
              
              # Skip pages 165-198
              $lineStart = ($pageNumber - 1) * 67 + 1
              if ($lineStart -ge (165 * 67) -and $lineStart -le (198 * 67)) {
                  if ($counter % 67 -eq 0) {
                      $pageNumber++
                      $counter = 0
                  }
                  return
              }
              
              # Stop after page 301
              if ($pageNumber -gt 301) {
                  return
              }
              
              # Output only lines 7-59 of each valid page, trimming first 40 characters
              if ($pagePosition -gt 6 -and $pagePosition -lt 60) {
                  if ($_.Length -gt 40) {
                      if ($_.Length -lt 48) { Write-Output "" }
                      else { Write-Output $_.Substring(48) }
                  }
              }
              
              if ($counter % 67 -eq 0) {
                  $pageNumber++
                  $counter = 0
              }
          } | Out-File -FilePath ALTAIRBASIC30_ASM_NOLINES.LST

      - name: Commit filtered file if updated
        shell: pwsh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ALTAIRBASIC30_ASM_LINES.LST
          git add ALTAIRBASIC30_ASM_NOLINES.LST
          # Only commit if there are changes
          $status = git status --porcelain
          if ($status) {
              git commit -m "Propagating changes from ALTAIRBASIC30.LST"
              git push
          }
          else {
              Write-Output "No changes to commit."
          }